---
title: "R Notebook"
output: html_notebook
---
So... this is me trying to plot a nice thing before trying other things

```{r}
#This line of code installs the pacman page if you do not have it installed - if you do, it simply loads the package
if(!require(pacman))install.packages("pacman")

pacman::p_load('dplyr', 'tidyr', 'gapminder',
               'ggplot2',  'ggalt',
               'forcats', 'R.utils', 'png', 
               'grid', 'ggpubr', 'scales',
               'bbplot')
```



```{r}
# Initial setup
library(ggplot2)
library(dplyr)
devtools::install_github('bbc/bbplot')

```


```{r}
# load package and data
options(scipen=999)  # turn-off scientific notation like 1e+48
library(ggplot2)
data("midwest", package = "ggplot2")
# midwest <- read.csv("http://goo.gl/G1K41K")  # bkup data source

# BBC Plot Notes:
# 1. It removes X and Y axis.

# Scatterplot - Way 1
plottest <- ggplot(midwest, aes(x=area, y=poptotal)) + 
  theme(panel.background = element_blank()) +
  geom_point(aes(col=state, size=popdensity)) + 
  geom_smooth(method="loess", se=F) + 
  xlim(c(0, 0.1)) + 
  ylim(c(0, 500000)) +
  bbc_style() +
  # Do not show size legend
  guides(size=FALSE) + 
  labs(subtitle="Area Vs Population", 
       y="Population", 
       x="Area", 
       title="Scatterplot", 
       caption = "Source: midwest")  + 
  theme(plot.title = element_text(size=22), plot.subtitle = element_text(size=14),
        legend.text=element_text(size=12),
        axis.text = element_text(size=12),
        # We can show again the axis with this command
        # axis.title = element_text(size=12)
        legend.justification = 'left',
        legend.text.align = 0
        ) 

plot(plottest)


# Scatterplot - Way 2
gg <- ggplot(midwest, aes(x=area, y=poptotal)) + 
  theme(panel.background = element_blank()) +
  geom_point(aes(col=state, size=popdensity)) + 
  geom_smooth(method="loess", se=F) + 
  xlim(c(0, 0.1)) + 
  ylim(c(0, 500000)) + 
  labs(subtitle="Area Vs Population", 
       y="Population", 
       x="Area", 
       title="Scatterplot", 
       caption = "Source: midwest") + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))

plot(gg)



```


```{r}
finalise_plot(plot_name = plottest,
              source = "Source: Gapminder",
              save_filepath = "plottest.png",
              width_pixels = 640,
              height_pixels = 640)
```

Ya que probe mas o menos como se harian las graficas (aunque no se ven taaan lindas), ahora a leer datos abiertos de Bogota

```{r}
library(httr)
library(jsonlite)
```


```{r}
res = GET("https://datosabiertos.bogota.gov.co/api/3/action/datastore_search?resource_id=b64ba3c4-9e41-41b8-b3fd-2da21d627558&limit=10000")
```

```{r}
db <- fromJSON(rawToChar(res$content))$result$records
db
```

Preprocessing dataframe

```{r}
old_names <-colnames(db)
new_names <- c('id', 'fecha_diagnostico', 'ciudad', 'localidad', 'edad', 'sexo', 'tipo_caso', 'ubicacion', 'estado')
db_clean <- db %>%
  rename_at(vars(old_names), ~new_names)
db_clean
```

Preprocessing per localidad

```{r}
db_grouped <- db_clean %>%
  group_by(localidad) %>%
  summarise(testing = n()) %>%
  mutate(localidad_lower = tolower(localidad))
db_grouped
```


Poblacion por localidad
http://www.sdp.gov.co/gestion-estudios-estrategicos/informacion-cartografia-y-estadistica/repositorio-estadistico/serie-poblacional-1995-2020-bogota-y-sus-localidades%5D

```{r}
library(readr)
library(R.utils)
db_localidad <- read_csv("PoblacionLocalidad - Sheet1.csv")
db_localidad <- db_localidad %>% 
  select(Localidad, "2020") %>%
  rename(poblacion_proyectada = "2020", localidad = Localidad) %>%
  mutate(localidad_lower = tolower(localidad))
db_localidad
```

